[project]
name = "oo-timestamps"
version = "0.1.0"
description = "Simple timestamps generator for Option Omega backtesting."
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "pandas>=2.3.1",
    "pandas-market-calendars>=4.3.3",
    "streamlit>=1.46.1",
]
